Repository milankl/StochasticRounding.jl, pull requests merged in 2023-07, with the labels that each got.

#67 Float16 stochastic round of subnormals
  src/float16sr.jl
  src/float32sr.jl
  test/float16sr.jl
  test/float32sr.jl
Labels: float16, subnormals

#66 show without Float??sr(...)
  src/bfloat16sr.jl
  src/float16sr.jl
  src/float32sr.jl
Labels: enhancement

#65 Added missing function definitions resolves #64
  src/bfloat16sr.jl
  src/float16sr.jl
  src/float32sr.jl
Labels: enhancement

#69 BFloat16s = "0.1,0.2,0.3,0.4"
  Project.toml
Labels: compatibility

#58 add Float32sr methods for DE.jl
  Project.toml
  src/StochasticRounding.jl
  src/bfloat16sr.jl
  src/float16sr.jl
  src/float32sr.jl
  src/general.jl
  src/promotion.jl
  test/differential_equations.jl
  test/runtests.jl
Labels: enhancement

#71 rand, randn, zeros, ones constructors
  src/StochasticRounding.jl
  src/bfloat16sr.jl
  src/float16sr.jl
  src/float32sr.jl
  src/float64sr.jl
Labels: enhancement
